#!/bin/bash

echo 'PWD:' `pwd`

device_number="0"

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[11,11,5]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[11,11,5]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[11,11,6]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[11,11,6]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[11,11,7]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[11,11,7]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[11,11,8]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[11,11,8]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[11,11,9]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[11,11,9]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[11,11,10]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[11,11,10]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[11,11,11]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[11,11,11]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[11,11,12]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[11,11,12]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[13,13,5]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[13,13,5]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[13,13,6]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[13,13,6]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[13,13,7]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[13,13,7]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[13,13,8]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[13,13,8]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[13,13,9]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[13,13,9]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[13,13,10]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[13,13,10]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[13,13,11]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[13,13,11]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[13,13,12]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[13,13,12]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[15,15,5]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[15,15,5]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[15,15,6]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[15,15,6]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[15,15,7]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[15,15,7]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[15,15,8]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[15,15,8]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[15,15,9]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[15,15,9]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[15,15,10]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[15,15,10]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[15,15,11]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[15,15,11]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[15,15,12]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[15,15,12]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[17,17,5]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[17,17,5]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[17,17,6]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[17,17,6]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[17,17,7]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[17,17,7]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[17,17,8]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[17,17,8]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[17,17,9]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[17,17,9]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[17,17,10]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[17,17,10]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[17,17,11]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[17,17,11]".0.log 2>&1

mcnnsantispoofing.py --dataset 0 --dataset_path dataset/NDCLD15 --ground_truth_path "" --iris_location extra/NDCLD15-with-OSIRIS-segmentation.csv/NDCLD15-with-OSIRIS-segmentation.csv --output_path tests/working_nov06 --descriptor bsif --desc_params "[17,17,12]" --operation crop --max_axis 260 --bs 32 --epochs 70 --lr 0.001 --decay 0.0 --last_layer softmax --loss_function 2 --optimizer 1 --reg 0.1 --n_jobs 6 --device_number $device_number --show_results > logs/livdet17.nov06.bsif."[17,17,12]".0.log 2>&1
